openapi: 3.0.0
info:
  title: Atomicbase API
  description: A REST API for managing and querying Turso databases.
  version: 0.1
servers:

paths:
  /query/{relation}:
    get:
      parameters:
        - in: query
          name: select
          schema:
            type: string
          required: false
      summary: Makes a SELECT query to a database based on the given query params.
      responses:
        "200": # status code
          description: A JSON array with one object for each row returned from the query.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
